# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
# app/config/services.yml
    app.repository.bookmark:
        class: AppBundle\Repository\BookmarkRepository
#app/config/services.yml
    app.repository.csvbookmark:
        class: AppBundle\Repository\BookmarkCsvRepository
# app/config/services.yml
    app.repository.tag:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Tag